### ISSUE TITLE
시간표 데이터베이스 관련 사양 지정

### ISSUE THREAD

**Issue by SeokjinDev** [KNUTPatAMat/Integrated-Information-Student-Management-System#3]
1안으로 유저 시간표에서는 학번, 시간으로 지정하고 각 시간에 수업 테이블의 id를 넣으려고 합니다.
이와 관련하여 수업 테이블에서는 수업 이름, 교수님 성함, 수업 설명 정도를 넣을까 합니다.

2안으로 유저 시간표에서 학번, 수업 관련 문자열을 넣을 수 있습니다.
이 경우 수업 관련 문자열에는 수업 테이블의 id를 문자열로 묶어서 넣게 됩니다.
수업 테이블에서는 수업 이름, 교수님 성함, 수업 시간, 수업 설명으로 들어감니다.

1안의 장점은 추가적인 데이터 처리가 필요 없다는 점이고
단점은 수업 시간 컬럼을 모두 생성해야한다는 점으로 초기 설정이 번거롭다는 점입니다.

2안의 장점은 생성하는 컬럼의 개수가 줄어 초기 설정이 편하다는 점이고
단점은 수업 문자열을 배열로 변경하는 과정이 들어가야 합니다.

1안과 2안 중 어떤 점이 좋을지 결정해주시기 바랍니다.

**Comment by k0ho817** [comment]
1안이 더 좋을것 같습니다

**Comment by SeokjinKim00** [comment]
1안에 문제점이 하나 존재하게 되었습니다.
하루의 시간표만 존재하면 1a, 1b 등으로 18개 가량의 컬럼이 존재합니다.
문제는 일주일 시간를 만들면 개수가 너무 많아진다는 점입니다.
때문에 1안을 조금 수정하여 학번, 월, 화, 수 ..., 일 이렇게 컬럼을 지정하고
각 컬럼에 0111100333 등으로 문자열 혹은 숫자로 그 날짜의 시간표를 지정하고자 합니다.
이렇게 문자열로 지정할 시에는 야간 수업 등에 대한 대응도 가능하다는 점에서 유연성도 늘어나는데
이러한 방법은 어떤가요?
