### ISSUE TITLE
DataBase 생성

### ISSUE THREAD

**Issue by k0ho817** [KNUTPatAMat/Integrated-Information-Student-Management-System#4]
Database/sql/teamdb.sql 퀴리문을 보니 TABLE DROP/CREATE/INSERT 코드만 있는것으로 확인하였는데
DATABASE 생성 쿼리문은 제가 직접 입력하여 생성 후 연결시켜 실행해야 하나요 ? 답변 부탁드립니다 !

**Comment by SeokjinDev** [comment]
Database를 생성하시는 이유가 어떻게 되시나요?
1. 코드로 db를 생성하는 메소드를 작성할 수는 있지만 필요성이 있나요?
2. table이 아닌 db를 새로 생성하려는 목적은 어떤 것인가요?

**Comment by k0ho817** [comment]
내부 코드에서 DB를 생성하는 기능을 만드는 것이 아니라
테스트를 위해서 똑같은 작업환경으로 세팅하려고 했습니다.

직접 생성 후
dbConnection()에 url수정으로 해결했습니다.

**Comment by SeokjinKim00** [comment]
넵
